root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main" 
cmd = "go build -o ./tmp/main ./cmd/processing-service/main.go" # Updated path to main.go
delay = 1000 
exclude_dir = ["vendor", "tmp"] 
include_ext = ["go", "tpl", "tmpl", "html"] 
kill_delay = "500ms" 
log = "build-errors.log" 
send_interrupt = true 
stop_on_error = true 

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
